CLASS ycl_test_sub_01 DEFINITION
  PUBLIC
  INHERITING FROM ycl_test_super_01
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ycl_test_sub_01 IMPLEMENTATION.
ENDCLASS.
